// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fkkpelzzmgbnwghebrli.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZra3BlbHp6bWdibndnaGVicmxpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0NDM3NDgsImV4cCI6MjA3MzAxOTc0OH0.Fq5le5tEbFpMafMUdnRL1s2EMLu6m1BorwYsouQTlX4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});